openapi: 3.0.3
info:
  title: earthquake-server
  version: 0.0.1

paths:
  /earthquake/{unid}:
    get:
      tags:
        - earthquake
      summary: Get a specific earthquake event
      parameters:
        - in: path
          name: unid
          schema:
            type: integer
          required: true
        - in: query
          name: expand
          schema:
            type: string
            enum: [address]
          description: Retrieves reverse geocoding info from geoapify and sets the value into the address field.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Earthquake'
        '404':
          description: Not found

  /earthquakes:
    get:
      tags:
        - earthquakes
      summary: List earthquakes (optional filtering and sort)
      parameters:
        - $ref: '#/components/parameters/date_from'
        - $ref: '#/components/parameters/date_to'
        - $ref: '#/components/parameters/country'
        - $ref: '#/components/parameters/sort'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EarthquakeListResponse'

    put:
      tags:
        - earthquakes
      summary: Resyncs earthquake data by fetching earthquakes from EMSC and storing them in db. If stale entries are present in the db, they will be overwrittern
      responses:
        '200':
           description: Success

  /earthquakes/{page}:
    get:
      tags:
        - earthquakes
      summary: Same as /earthquakes endpoint but with pagination
      parameters:
        - in: path
          name: page
          description: Specifies page in results list, 100 results per page. Page numbering is 1-indexed
          required: true
          schema:
            type: integer
        - $ref: '#/components/parameters/date_from'
        - $ref: '#/components/parameters/date_to'
        - $ref: '#/components/parameters/country'
        - $ref: '#/components/parameters/sort'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EarthquakeListResponse'

components:
  parameters:
    date_from:
      in: query
      name: date_from
      schema:
        type: string
      description: Filters results to only include events with time >= this value
      required: false
    date_to:
      in: query
      name: date_to
      schema:
        type: string
      description: Filters results to only include events with time < this value
      required: false
    country:
      in: query
      name: country
      schema:
        type: string
      description: Filters results by partial match on flynn_region property
    sort:
      in: query
      name: sort
      schema:
        type: string
      description: 'Sort results. Syntax: comma-seperated list of "column_name order" values'
      example: time desc,mag asc
  schemas:
    EarthquakeListResponse:
      type: object
      properties:
        entries:
          type: array
          items:
            $ref: '#/components/schemas/Earthquake'
        total:
          type: integer
          description: total number of results on server
        page:
          type: integer
          description: current page
        page_size:
          type: integer
          description: current page size
    Earthquake:
      type: object
      properties:
        id:
          type: string
          example: '20240412_0000228'
        mag:
          type: string
          example: 2.6
        lon:
          type: number
          example: 80.51
        lat:
          type: number
          example: 30.24
        depth:
          type: number
          example: 5
        lastupdate:
          type: string
          example: 2024-04-12T20:07:37.13824Z
        time:
          type: string
          example: 2024-04-12T19:59:07.0Z
        magtype:
          type: string
          example: m
        evtype:
          type: string
          example: ke
        auth:
          type: string
          example: NDI
        source_id:
          type: string
          example: 1645954
        source_catalog:
          type: string
          example: EMSC-RTS
        flynn_region:
          type: string
          example: CROATIA
        address:
          type: string
          example: Gornji Bukovac, 10153 City of Zagreb, Croatia
          description: This property is only populated in the /earthquake/{unid}?expand=address call
